export const bags = [
  {
    id: 1,
    imageUrl: './assets/images/products/everest_bag.jpg',
    title: 'Everest Gym Bag with Wet Pocket, Red, One Size ',
    name: 'everest-gym-bag',
    price: '22.48',
    brand: 'everest',
  },
  {
    id: 2,
    imageUrl: './assets/images/products/ua_bag.jpg',
    title: 'Under Armour Undeniable 3.0 Duffle',
    name: 'under-armour-gym-bag',
    price: '34.99',
    brand: 'under-armour',
  },
  {
    id: 3,
    imageUrl: './assets/images/products/adidas_diablo_bag.jpg',
    title: ' adidas Diablo Small Duffel Bag ',
    name: 'adidas-diablo-bag',
    price: '25.00',
    brand: 'adidas',
  },
  {
    id: 4,
    imageUrl: './assets/images/products/adidas_defender_3_bag.jpg',
    title: 'adidas Defender III Duffel Bag',
    name: ' adidas-defender-3-bag ',
    price: '25.00',
    brand: 'adidas',
  },
  {
    id: 5,
    imageUrl: './assets/images/products/nike_brasilia_training_bag.jpg',
    title: 'NIKE Brasilia Medium Training Duffel Bag',
    name: 'nike-brasilia-training-bag',
    price: '31.99',
    brand: 'nike',
  },
  {
    id: 6,
    imageUrl: './assets/images/products/luggage_sporty_gear_bag.jpg',
    title: 'Luggage Sporty Gear Bag - Large, Dark Purple',
    name: 'luggage-sporty-gear-bag',
    price: '26.49',
    brand: 'everest',
  },
  {
    id: 7,
    imageUrl: './assets/images/products/fila_small_gym_bag.jpg',
    title: 'Advantage Small Duffel Gym Sports Bag with Shoe Compartment',
    name: 'fila-small-gym-bag',
    price: '23.49',
    brand: 'fila',
  },
  {
    id: 8,
    imageUrl: './assets/images/products/puma_evercat_dispatch_duffel.jpg',
    title: 'PUMA Evercat Dispatch Duffel',
    name: 'puma-evercat-dispatch-duffel',
    price: '20.00',
    brand: 'puma',
  },
  {
    id: 9,
    imageUrl: './assets/images/products/starter_duffle_gym_bag.jpg',
    title: 'Starter 21" Duffle Gym Bag',
    name: 'starter-duffle-gym-bag',
    price: '20.00',
    brand: 'starter',
  },
  {
    id: 10,
    imageUrl: './assets/images/products/adidas_santiago_duffel_bag.jpg',
    title: 'adidas Santiago Duffel Bag',
    name: 'adidas-santiago-duffel-bag',
    price: '39.99',
    brand: 'adidas',
  },
  {
    id: 11,
    imageUrl: './assets/images/products/adidas_studio_duffel_bag.jpg',
    title: 'Adidas Studio Duffel Bag',
    name: 'adidas-studio-duffel-bag',
    price: '44.95',
    brand: 'adidas',
  },
  {
    id: 12,
    imageUrl: './assets/images/products/fila_large_duffel_bag.jpg',
    title: 'Acer Large Duffel Gym Sports Bag',
    name: 'acer-large-duffel-bag',
    price: '27.99',
    brand: 'fila',
  },
  {
    id: 13,
    imageUrl: './assets/images/products/adidas_unisex_duffel_bag.jpg',
    title: 'adidas Unisex Sport ID Duffel',
    name: 'adidas-unisex-duffel-bag',
    price: '65.00',
    brand: 'adidas',
  },
  {
    id: 14,
    imageUrl: './assets/images/products/nike_brasilia_duffel_bag.jpg',
    title: 'NIKE Brasilia Medium Duffel Bag',
    name: 'nike-brasilia-duffel-bag',
    price: '40.00',
    brand: 'nike',
  },
  {
    id: 15,
    imageUrl: './assets/images/products/bando_i_did_my_best_gym_bag.jpg',
    title: 'ban.do Work It Out I Did My Best Gym Bag',
    name: 'bando-i-did-my-best-gym-bag',
    price: '35.00',
    brand: 'bando',
  },
  {
    id: 16,
    imageUrl: './assets/images/products/luggage_sporty_gear_bag.jpg',
    title: 'Luggage Sporty Gear Bag - Large, Dark Purple',
    name: 'luggage-sporty-gear-bag',
    price: '26.49',
    brand: 'everest',
  },
  {
    id: 17,
    imageUrl: './assets/images/products/fila_small_gym_bag.jpg',
    title: 'Advantage Small Duffel Gym Sports Bag with Shoe Compartment',
    name: 'fila-small-gym-bag',
    price: '23.49',
    brand: 'fila',
  },
  {
    id: 18,
    imageUrl: './assets/images/products/puma_evercat_dispatch_duffel.jpg',
    title: 'PUMA Evercat Dispatch Duffel',
    name: 'puma-evercat-dispatch-duffel',
    price: '20.00',
    brand: 'puma',
  },
  {
    id: 19,
    imageUrl: './assets/images/products/starter_duffle_gym_bag.jpg',
    title: 'Starter 21" Duffle Gym Bag',
    name: 'starter-duffle-gym-bag',
    price: '20.00',
    brand: 'starter',
  },
  {
    id: 20,
    imageUrl: './assets/images/products/adidas_santiago_duffel_bag.jpg',
    title: 'adidas Santiago Duffel Bag',
    name: 'adidas-santiago-duffel-bag',
    price: '39.99',
    brand: 'adidas',
  },
  {
    id: 21,
    imageUrl: './assets/images/products/everest_bag.jpg',
    title: 'Everest Gym Bag with Wet Pocket, Red, One Size ',
    name: 'everest-gym-bag',
    price: '22.48',
    brand: 'everest',
  },
  {
    id: 22,
    imageUrl: './assets/images/products/ua_bag.jpg',
    title: 'Under Armour Undeniable 3.0 Duffle',
    name: 'under-armour-gym-bag',
    price: '34.99',
    brand: 'under-armour',
  },
  {
    id: 23,
    imageUrl: './assets/images/products/adidas_diablo_bag.jpg',
    title: ' adidas Diablo Small Duffel Bag ',
    name: 'adidas-diablo-bag',
    price: '25.00',
    brand: 'adidas',
  },
  {
    id: 24,
    imageUrl: './assets/images/products/adidas_defender_3_bag.jpg',
    title: 'adidas Defender III Duffel Bag',
    name: ' adidas-defender-3-bag ',
    price: '25.00',
    brand: 'adidas',
  },
  {
    id: 25,
    imageUrl: './assets/images/products/nike_brasilia_training_bag.jpg',
    title: 'NIKE Brasilia Medium Training Duffel Bag',
    name: 'nike-brasilia-training-bag',
    price: '31.99',
    brand: 'nike',
  },
  {
    id: 26,
    imageUrl: './assets/images/products/meister_vented_gym_bag.jpg',
    title: 'Meister Vented Convertible Duffel/Backpack Gym Bag - Ideal Carry-On ',
    name: 'meister-vented-gym-bag',
    price: '39.00',
    brand: 'meister',
  },
];
export const hoodies = [
  {
    id: 126,
    imageUrl: './assets/images/products/coolred_pineapple_hoodie.jpg',
    title: 'Coolred Long Sleeve Pineapple Hood Hoodies Drawstring Outwear',
    name: 'coolred-pineapple-hoodie',
    price: '8.61',
    brand: 'coolred',
    gender: 'female',
  },
  {
    id: 127,
    imageUrl: './assets/images/products/marilyn_monroe_fleece_zipper_hoodie.jpg',
    title: 'Thug Headband Marilyn Monroe Fleece Zipper Hoodie',
    name: 'marilyn-monroe-fleece-zipper-hoodie',
    price: '12.99',
    brand: 'interstate-apparel',
    gender: 'female',
  },
  {
    id: 128,
    imageUrl: './assets/images/products/ua_women_storm_caliber_hoodie.jpg',
    title: 'Under Armour Women\'s Storm Caliber Hoodie',
    name: 'ua-women-storm-caliber-hoodie',
    price: '34.92',
    brand: 'under-armour',
    gender: 'female',
  },
  {
    id: 129,
    imageUrl: './assets/images/products/ua_women_armour_fleece_hoodie.jpg',
    title: 'Under Armour Womens Armour Fleece Hoodie',
    name: 'ua-women-armour-fleece-hoodie',
    price: '32.99',
    brand: 'under-armour',
    gender: 'female',
  },
  {
    id: 130,
    imageUrl: './assets/images/products/ua_women_armour_caliber_hoodie.jpg',
    title: 'Under Armour Womens Icon Caliber Hoodie',
    name: 'ua-women-armour-caliber-hoodie',
    price: '27.64',
    brand: 'under-armour',
    gender: 'female',
  },
  {
    id: 131,
    imageUrl: './assets/images/products/adidas_women_originals_cutout_sweater.jpg',
    title: 'Adidas Women Originals Cutout Sweater',
    name: 'adidas-women-originals-cutout-sweater',
    price: '63.00',
    brand: 'adidas',
    gender: 'female',
  },
  {
    id: 132,
    imageUrl: './assets/images/products/hanes_women_fleece_hoodie.jpg',
    title: 'Hanes Sport Women\'s Performance Fleece Full Zip Hoodie ',
    name: 'hanes-women-fleece-hoodie',
    price: '30.79',
    brand: 'hanes',
    gender: 'female',
  },
  {
    id: 133,
    imageUrl: './assets/images/products/champion_powerblend_fleece_hoodie.jpg',
    title: 'Champion Men\'s Powerblend Fleece Pullover Hoodie',
    name: 'champion-powerblend-fleece-hoodie',
    price: '30.79',
    brand: 'champion',
    gender: 'male',
  },
  {
    id: 134,
    imageUrl: './assets/images/products/hanes_men_fleece_hoodie.jpg',
    title: 'Hanes Men\'s Pullover EcoSmart Fleece Hooded Sweatshirt',
    name: 'hanes-men-fleece-hoodie',
    price: '50.31',
    brand: 'hanes',
    gender: 'male',
  },
  {
    id: 135,
    imageUrl: './assets/images/products/nike_men_club_hoodie.jpg',
    title: 'NIKE Sportswear Men\'s Pullover Club Hoodie',
    name: 'nike-men-club-hoodie',
    price: '39.98',
    brand: 'nike',
    gender: 'male',
  },
  {
    id: 136,
    imageUrl: './assets/images/products/champion_reverse_pullover_hoodie.jpg',
    title: 'Champion Men\'s Reverse Weave Pullover Hoodie ',
    name: 'champion-reverse-pullover-hoodie',
    price: '37.00',
    brand: 'champion',
    gender: 'male',
  },
  {
    id: 137,
    imageUrl: './assets/images/products/alternative_eco_zip_hoodie.jpg',
    title: 'Alternative Men\'s Eco Zip Hoodie Sweatshirt',
    name: 'alternative-eco-zip-hoodie',
    price: '17.97',
    brand: 'alternative',
    gender: 'male',
  },
  {
    id: 138,
    imageUrl: './assets/images/products/nike_men_zip_hoodie.jpg',
    title: 'NIKE Sportswear Men\'s Half Zip Club Fleece Hooded Sweatshirt ',
    name: 'nike-men-zip-hoodie',
    price: '34.02',
    brand: 'nike',
    gender: 'male',
  },
  {
    id: 139,
    imageUrl: './assets/images/products/nike_men_full_zip_hoodie.jpg',
    title: 'NIKE Sportswear Men\'s Full-Zip Hoodie',
    name: 'nike-men-full-zip-hoodie',
    price: '63.00',
    brand: 'nike',
    gender: 'male',
  },
  {
    id: 140,
    imageUrl: './assets/images/products/mission_men_fleece_hoodie.jpg',
    title: ' Mission Men\'s Pullover Fleece Hoodie ',
    name: 'mission-men-fleece-hoodie',
    price: '23.10',
    brand: 'mission',
    gender: 'male',
  },
  {
    id: 141,
    imageUrl: './assets/images/products/coolred_pineapple_hoodie.jpg',
    title: 'Coolred Long Sleeve Pineapple Hood Hoodies Drawstring Outwear',
    name: 'coolred-pineapple-hoodie',
    price: '8.61',
    brand: 'coolred',
    gender: 'female',
  },
  {
    id: 142,
    imageUrl: './assets/images/products/marilyn_monroe_fleece_zipper_hoodie.jpg',
    title: 'Thug Headband Marilyn Monroe Fleece Zipper Hoodie',
    name: 'marilyn-monroe-fleece-zipper-hoodie',
    price: '12.99',
    brand: 'interstate-apparel',
    gender: 'female',
  },
  {
    id: 143,
    imageUrl: './assets/images/products/ua_women_storm_caliber_hoodie.jpg',
    title: 'Under Armour Women\'s Storm Caliber Hoodie',
    name: 'ua-women-storm-caliber-hoodie',
    price: '34.92',
    brand: 'under-armour',
    gender: 'female',
  },
  {
    id: 144,
    imageUrl: './assets/images/products/ua_women_armour_fleece_hoodie.jpg',
    title: 'Under Armour Womens Armour Fleece Hoodie',
    name: 'ua-women-armour-fleece-hoodie',
    price: '32.99',
    brand: 'under-armour',
    gender: 'female',
  },
  {
    id: 145,
    imageUrl: './assets/images/products/ua_women_armour_caliber_hoodie.jpg',
    title: 'Under Armour Womens Icon Caliber Hoodie',
    name: 'ua-women-armour-caliber-hoodie',
    price: '27.64',
    brand: 'under-armour',
    gender: 'female',
  },
  {
    id: 146,
    imageUrl: './assets/images/products/champion_powerblend_fleece_hoodie.jpg',
    title: 'Champion Men\'s Powerblend Fleece Pullover Hoodie',
    name: 'champion-powerblend-fleece-hoodie',
    price: '30.79',
    brand: 'champion',
    gender: 'male',
  },
  {
    id: 147,
    imageUrl: './assets/images/products/hanes_men_fleece_hoodie.jpg',
    title: 'Hanes Men\'s Pullover EcoSmart Fleece Hooded Sweatshirt',
    name: 'hanes-men-fleece-hoodie',
    price: '50.31',
    brand: 'hanes',
    gender: 'male',
  },
  {
    id: 148,
    imageUrl: './assets/images/products/nike_men_club_hoodie.jpg',
    title: 'NIKE Sportswear Men\'s Pullover Club Hoodie',
    name: 'nike-men-club-hoodie',
    price: '39.98',
    brand: 'nike',
    gender: 'male',
  },
  {
    id: 149,
    imageUrl: './assets/images/products/champion_reverse_pullover_hoodie.jpg',
    title: 'Champion Men\'s Reverse Weave Pullover Hoodie ',
    name: 'champion-reverse-pullover-hoodie',
    price: '37.00',
    brand: 'champion',
    gender: 'male',
  },
  {
    id: 150,
    imageUrl: './assets/images/products/alternative_eco_zip_hoodie.jpg',
    title: 'Alternative Men\'s Eco Zip Hoodie Sweatshirt',
    name: 'alternative-eco-zip-hoodie',
    price: '17.97',
    brand: 'alternative',
    gender: 'male',
  },
];
export const orders = [
  {
    id: 1,
    status: 'delivery',
    client: {
      name: 'Jon Doe',
      email: 'jondoe@gmail.com',
    },
    shipTo: 'Jon Doe, Santiago st. 322, Lisaboa, Portugal',
    total: '12.99',
  },
  {
    id: 2,
    status: 'pending',
    client: {
      name: 'Sandra Seagel',
      email: 'sansea@gmail.com',
    },
    shipTo: 'Sandra Seagel, Jose st. 65, Murcia, Spain',
    total: '54.43',
  },
  {
    id: 3,
    status: 'completed',
    client: {
      name: 'Matt Don',
      email: 'mattdon@gmail.com',
    },
    shipTo: 'Matt Don, Braun st. 92, Berlin, Germany',
    total: '75.13',
  },
  {
    id: 4,
    status: 'delivery',
    client: {
      name: 'Luis Sicon',
      email: 'luis@gmail.com',
    },
    shipTo: 'Luis Sicon, Bologne st. 76, Rome, Italy',
    total: '45.55',
  },
  {
    id: 5,
    status: 'pending',
    client: {
      name: 'Ora Lion',
      email: 'oralion@gmail.com',
    },
    shipTo: 'Ora Lion, Sheez st. 45, Venice, Italy',
    total: '15.63',
  },
  {
    id: 6,
    status: 'completed',
    client: {
      name: 'Tomasz Modri',
      email: 'tomasz@gmail.com',
    },
    shipTo: 'Tomasz Modri, Berlin st. 224, Warsaw, Poland',
    total: '90.12',
  },
  {
    id: 7,
    status: 'delivery',
    client: {
      name: 'Ingi Laus',
      email: 'ingilaus@gmail.com',
    },
    shipTo: 'Ingi Laus, Braun st. 77, Talinn, Estonia',
    total: '33.89',
  },
  {
    id: 8,
    status: 'completed',
    client: {
      name: 'Olga Ribak',
      email: 'ribakol@gmail.com',
    },
    shipTo: 'Olga Ribak, Zuvi st. 2, Riga, Latvia',
    total: '92.56',
  },
  {
    id: 9,
    status: 'pending',
    client: {
      name: 'Luka Modri',
      email: 'lukamodri@gmail.com',
    },
    shipTo: 'Luka Modri, Opoli st. 567, Nudi, Croatia',
    total: '112.87',
  },
  {
    id: 10,
    status: 'delivery',
    client: {
      name: 'Juan Dam',
      email: 'Dam@gmail.com',
    },
    shipTo: 'Juan Dam, Baget st. 73, Paris, France',
    total: '67.98',
  },
  {
    id: 11,
    status: 'completed',
    client: {
      name: 'Jon Doe',
      email: 'jondoe@gmail.com',
    },
    shipTo: 'Jon Doe, Santiago st. 322, Lisaboa, Portugal',
    total: '12.99',
  },
  {
    id: 12,
    status: 'delivery',
    client: {
      name: 'Sandra Seagel',
      email: 'sansea@gmail.com',
    },
    shipTo: 'Sandra Seagel, Jose st. 65, Murcia, Spain',
    total: '54.43',
  },
  {
    id: 13,
    status: 'completed',
    client: {
      name: 'Matt Don',
      email: 'mattdon@gmail.com',
    },
    shipTo: 'Matt Don, Braun st. 92, Berlin, Germany',
    total: '75.13',
  },
  {
    id: 14,
    status: 'completed',
    client: {
      name: 'Luis Sicon',
      email: 'luis@gmail.com',
    },
    shipTo: 'Luis Sicon, Bologne st. 76, Rome, Italy',
    total: '45.55',
  },
  {
    id: 15,
    status: 'delivery',
    client: {
      name: 'Ora Lion',
      email: 'oralion@gmail.com',
    },
    shipTo: 'Ora Lion, Sheez st. 45, Venice, Italy',
    total: '15.63',
  },
  {
    id: 16,
    status: 'completed',
    client: {
      name: 'Tomasz Modri',
      email: 'tomasz@gmail.com',
    },
    shipTo: 'Tomasz Modri, Berlin st. 224, Warsaw, Poland',
    total: '90.12',
  },
  {
    id: 17,
    status: 'completed',
    client: {
      name: 'Ingi Laus',
      email: 'ingilaus@gmail.com',
    },
    shipTo: 'Ingi Laus, Braun st. 77, Talinn, Estonia',
    total: '33.89',
  },
  {
    id: 18,
    status: 'completed',
    client: {
      name: 'Olga Ribak',
      email: 'ribakol@gmail.com',
    },
    shipTo: 'Olga Ribak, Zuvi st. 2, Riga, Latvia',
    total: '92.56',
  },
  {
    id: 19,
    status: 'delivery',
    client: {
      name: 'Luka Modri',
      email: 'lukamodri@gmail.com',
    },
    shipTo: 'Luka Modri, Opoli st. 567, Nudi, Croatia',
    total: '112.87',
  },
  {
    id: 20,
    status: 'completed',
    client: {
      name: 'Juan Dam',
      email: 'Dam@gmail.com',
    },
    shipTo: 'Juan Dam, Baget st. 73, Paris, France',
    total: '67.98',
  },
];
export const filters = [
  { id: 1, name: 'adidas', isChecked: false },
  { id: 2, name: 'nike', isChecked: false },
  { id: 3, name: 'under-armour', isChecked: false },
  { id: 4, name: 'puma', isChecked: false },
  { id: 5, name: 'fila', isChecked: false },
];
export const products = [...bags, ...hoodies];
export const data = {
  products,
  orders,
};
